# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  name: local

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.15.0'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- script: |
    npx truffle test
  displayName: 'run tests'

- script: |
    cd src
    npx truffle compile contracts/$(contractName).sol
  displayName: 'Compile smart contract'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/src/abis/$(contractName).json'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(contractName)-$(Build.BuildId).zip'
  displayName: 'Archiving contract $(contractName)'
