# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

variables:
  contractName: 'DocumentIdentifier'

pool:
  name: local

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.15.0'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'NPM Install/Build'

- script: |
    npm install solhint
    npx solhint --init
  displayName: 'Configure Linter'

- script: |
    npx solhint contracts/$(contractName).sol > linter-log.txt 2>&1
    if [ $? -ne 0 ]; then
      echo "##vso[task.setvariable variable=linterLog]$(cat linter-log.txt | sed '1,/> solhint ./d;/npm ERR!/,$d' | sed '/./,$!d' | sed ':a;N;$!ba;s/\n/%0D%0A/g')"
    fi
  continueOnError: true
  displayName: 'Run Linter'
- task: GitHubComment@0
  condition: and(eq(variables['Build.Reason'], 'PullRequest'), failed())
  inputs:
    gitHubConnection: 'alvarojry'
    repositoryName: '$(Build.Repository.Name)'
    comment: |
      **Linter Error Details:**
      ```
      $(linterLog)
      ```

- script: |
    npx truffle test
  displayName: 'Run Unit Tests'

- script: |
    cd src
    npx truffle compile contracts/$(contractName).sol
  displayName: 'Compile smart contract'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/src/abis/$(contractName).json'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(contractName)-$(Build.BuildId).zip'
  displayName: 'Archiving contract $(contractName)'
